# Generated by Django 5.2.8 on 2025-11-28 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('town', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='slug',
            field=models.SlugField(default='-', max_length=100),
            preserve_default=False,
        ),
    ]
