# Generated by Django 5.2.8 on 2025-12-07 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('town', '0002_house_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='svg_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
